name: 'Apply Label Using AI'

description: 'Use AI to find the best label to apply to a new issue'

inputs:
  labels:
    description: 'The list of labels available.'
  label-pattern:
    description: 'The regex pattern to use to match the labels.'
  issue-json:
    description: 'The json object of the issue to be labeled.'
    deprecationMessage: 'This is deprecated and will be removed.'

# outputs:
#   label:
#     description: "The label that will be applied to the issue"
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:

    - name: Read the test issue json if it is provided
      shell: pwsh
      id: loader
      if: ${{ inputs.issue-json != null }}
      env:
        ISSUE_JSON: ${{ inputs.issue-json }}
      run: |
        $issue = $env:ISSUE_JSON | Join-String -Separator " "
        "GITHUB_ISSUE_DEPRECATED=$issue" >> $env:GITHUB_OUTPUT
    
    - name: Do something when an issue is opened
      id: get-label
      shell: pwsh
      env:
        GITHUB_ISSUE: ${{ steps.loader.outputs.GITHUB_ISSUE }}
        GITHUB_ISSUE_DEPRECATED: ${{ steps.loader.outputs.GITHUB_ISSUE_DEPRECATED }}
        GH_TOKEN: ${{ github.token }}
        LABEL_PATTERN: ${{ inputs.label-pattern }}
      run: |
        Write-Host "$env:GITHUB_ISSUE"
        Write-Host "$env:GITHUB_ISSUE_DEPRECATED"
        if (-not $env:GITHUB_ISSUE) {
          $issue = "$env:GITHUB_ISSUE_DEPRECATED" | ConvertFrom-Json
        } else {
          $issue = "$env:GITHUB_ISSUE" | ConvertFrom-Json
        }
        
        $repoUrl = "${{ github.repositoryUrl }}"

        Write-Host "Repository URL: $repoUrl"
        Write-Host "Issue Url: $($issue.html_url)"
        Write-Host "Issue Title: $($issue.title)"

        $labelRegex = "$env:LABEL_PATTERN"
        $labelSelector = "[.[] | select(.name | test(`"$labelRegex`"))]"
        $labelsResult = gh label list --repo "$repoUrl" --json name --jq "$labelSelector"
        $labels = $labelsResult | ConvertFrom-Json
        Write-Host $labels
        $labelsNames = $labels | Select-Object -ExpandProperty name

        Write-Host "Filtered Labels:"
        Write-Host $labelsNames

        $hostAddress = "https://labeled-by-ai.yellowhill-0060a70b.southafricanorth.azurecontainerapps.io"
        $uri = "$hostAddress/api/label"
        $bodyObj = @{
            title = $issue.title
            body = $issue.body
            url = $issue.html_url
            labels = $labelsNames
        }
        $body = $bodyObj | ConvertTo-Json

        Write-Host "Request Body:"
        Write-Host $body

        $response = Invoke-RestMethod `
          -Method Post `
          -Uri $uri `
          -Body $body `
          -ContentType 'application/json'

        Write-Host "Response:"
        Write-Host $response

        # TODO: Apply the labels to the issue

        echo "DONE!"
