name: 'Update Engagement Scores'

description: 'Update engagement scores in a project'

inputs:
  project:
    description: 'The project to update the scores in.'
    required: true
  column:
    description: 'The column in which to update the scores.'
    default: 'Engagement Score'
  classification-column:
    description: 'The column in which to update the classification.'
    default: 'Engagement Classification'
  project-token:
    description: 'The GitHub token to use when updating the project.'
    required: true
  update-project:
    description: 'Whether or not to update the project items with the score.'
    default: 'true'

runs:
  using: "composite"
  steps:

    - name: Update the engagement scores
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.project-token }}
        GITHUB_TOKEN: ${{ inputs.project-token }}
        PROJECT_OWNER: ${{ github.event.repository.owner.login }}
        PROJECT_REPO: ${{ github.event.repository.name }}
        PROJECT_NUMBER: ${{ inputs.project }}
        PROJECT_ENGAGEMENT_FIELD_NAME: ${{ inputs.column }}
        PROJECT_CLASSIFICATION_FIELD_NAME: ${{ inputs.classification-column }}
        UPDATE_PROJECT: ${{ inputs.update-project }}
      run: |
        "Calculating the engagement scores..."

        Write-Output "::group::Sending the request to the server..."
        $body = ConvertTo-Json -InputObject @{
          version = 1
          project = @{
            owner = "$env:PROJECT_OWNER"
            number = "$env:PROJECT_NUMBER"
          }
        }

        Write-Output "JSON Body:"
        Write-Output $body

        $hostAddress = "https://labeled-by-ai.braveisland-12c152b6.southafricanorth.azurecontainerapps.io"
        $uri = "$hostAddress/api/engagement-score"
        $headers = @{
          'X-GitHub-Token' = "$env:GITHUB_TOKEN"
        }
        $response = Invoke-RestMethod `
          -Method Post `
          -Uri $uri `
          -Body $body `
          -ContentType 'application/json' `
          -Headers $headers `
          -StatusCodeVariable responseStatusCode

        Write-Output "The server replied with a status code of: $responseStatusCode"

        if (-not $response) {
          Write-Error "Failed to get a response from the server."
          Write-Output "::endgroup::"
          exit 1
        }

        if ($response.Count -eq 0) {
          Write-Warning "No open issues were found."
          Write-Output "::endgroup::"
          exit 0
        }

        Write-Output "::endgroup::"

        Write-Output "::group::Updating the scores in the project..."

        Write-Output "Reading the project information..."
        $projectId = $response.project.id
        $projectNumber = $response.project.number
        $projectOwner = $response.project.owner
        $projectUpdateCount = $response.totalItems
        Write-Output "Project Details:"
        Write-Output "  ID: $projectId"
        Write-Output "  Owner: $projectOwner"
        Write-Output "  Number: $projectNumber"
        Write-Output "  Items to Update: $projectUpdateCount"

        Write-Output "Loading the project fields..."
        $fields = gh project field-list `
            $projectNumber `
            --owner "$projectOwner" `
            --format json |
          ConvertFrom-Json |
          Select-Object -ExpandProperty fields

        if (-not "$env:PROJECT_ENGAGEMENT_FIELD_NAME") {
          Write-Output "The engagement score field name was not provided, so will not update."
        } else {
          $scoreField = $fields | Where-Object { $_.name -eq "$env:PROJECT_ENGAGEMENT_FIELD_NAME" }
          if (-not $scoreField) {
            Write-Warning "Score field '$env:PROJECT_ENGAGEMENT_FIELD_NAME' was not found."
          } else {
            $scoreFieldId = $scoreField.id
            $scoreFieldName = $scoreField.name
            Write-Output "  Score Field Details:"
            Write-Output "    ID: $scoreFieldId"
            Write-Output "    Name: $scoreFieldName"
          }
        }

        if (-not "$env:PROJECT_CLASSIFICATION_FIELD_NAME") {
          Write-Output "The engagement classification field name was not provided, so will not update."
        } else {
          $classificationField = $fields | Where-Object { $_.name -eq "$env:PROJECT_CLASSIFICATION_FIELD_NAME" }
          if (-not $classificationField) {
            Write-Warning "Classification field '$env:PROJECT_CLASSIFICATION_FIELD_NAME' was not found."
          } else {
            $classificationFieldId = $classificationField.id
            $classificationFieldName = $classificationField.name
            $classificationFieldOptions = @{}
            foreach ($option in $classificationField.options) {
                $classificationFieldOptions[$option.name.ToLower()] = $option.id
            }
            Write-Output "  Classification Field Details:"
            Write-Output "    ID: $classificationFieldId"
            Write-Output "    Name: $classificationFieldName"
            Write-Output "    Options: $(@($classificationFieldOptions.Keys) -join ', ')"
          }
        }

        if (-not $scoreField -and -not $classificationField) {
          Write-Output "No fields were found to update."
          Write-Output "::endgroup::"
          exit 0
        }

        Write-Output "Updating the scores in the project..."
        foreach ($item in $response.items) {
          $itemId = $item.id
          $repository = "$($item.issue.owner)/$($item.issue.repo)"
          $issueNumber = $item.issue.number
          $engagementScore = $item.engagement.score
          $classification = $item.engagement.classification

          Write-Output "  $repository#$issueNumber => $engagementScore"

          if ($env:UPDATE_PROJECT -eq 'true') {
            if ($scoreField) {
              gh project item-edit `
                --id "$itemId" `
                --project-id "$projectId" `
                --field-id "$scoreFieldId" `
                --number "$engagementScore"
            }
            if ($classificationField -and $classification -eq 'hot') {
              gh project item-edit `
                --id "$itemId" `
                --project-id "$projectId" `
                --field-id "$classificationFieldId" `
                --single-select-option-id $classificationFieldOptions['hot']
            }
          }
        }

        Write-Output "::endgroup::"
