name: 'Apply Label Using AI'

description: 'Use AI to find the best label to apply to a new issue'

inputs:
  labels:
    description: 'The list of labels available.'
  label-pattern:
    description: 'The regex pattern to use to match the labels.'
  issue-json:
    description: 'The json object of the issue to be labeled.'
    deprecationMessage: 'This is deprecated and will be removed.'

# outputs:
#   label:
#     description: "The label that will be applied to the issue"
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:

    - name: Do something when an issue is opened
      id: get-label
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}                       # for the gh CLI tool
        GITHUB_ISSUE: ${{ toJson(github.event.issue) }}     # the issue json from the event
        LABEL_PATTERN: ${{ inputs.label-pattern }}          # the label pattern to match
        GITHUB_ISSUE_DEPRECATED: ${{ inputs.issue-json }}   # testing purposes only
      run: |
        # Parse the issue json from the event or fall back
        # to the deprecated method of reading the issue json
        # from the environment variable
        $issue = "$env:GITHUB_ISSUE" | ConvertFrom-Json
        if (-not $issue) {
          $issue = "$env:GITHUB_ISSUE_DEPRECATED" | ConvertFrom-Json
        }
        
        $repoUrl = "${{ github.repositoryUrl }}"

        Write-Output "::debug::GITHUB_ISSUE: $env:GITHUB_ISSUE"
        Write-Output "::debug::GITHUB_ISSUE_DEPRECATED: $env:GITHUB_ISSUE_DEPRECATED"
        Write-Output "::debug::issue: $issue"
        Write-Output "::debug::Repository URL: $repoUrl"
        Write-Output "::debug::Issue Url: $($issue.html_url)"
        Write-Output "::debug::Issue Title: $($issue.title)"

        $labelRegex = "$env:LABEL_PATTERN"
        $labelSelector = "[.[] | select(.name | test(`"$labelRegex`"))]"
        $labelsResult = gh label list --repo "$repoUrl" --json name --jq "$labelSelector"
        $labels = $labelsResult | ConvertFrom-Json
        Write-Output "::debug::$labels"
        $labelsNames = $labels | Select-Object -ExpandProperty name

        Write-Output "::debug::Filtered Labels:"
        Write-Output "::debug::$labelsNames"

        $hostAddress = "https://labeled-by-ai.yellowhill-0060a70b.southafricanorth.azurecontainerapps.io"
        $uri = "$hostAddress/api/label"
        $bodyObj = @{
            title = $issue.title
            body = $issue.body
            url = $issue.html_url
            labels = $labelsNames
        }
        $body = $bodyObj | ConvertTo-Json

        Write-Output "::debug::Request Body:"
        Write-Output "::debug::$body"

        $response = Invoke-RestMethod `
          -Method Post `
          -Uri $uri `
          -Body $body `
          -ContentType 'application/json'

        Write-Output "::debug::Response:"
        Write-Output "::debug::$response"

        # TODO: Apply the labels to the issue

        echo "DONE!"
