# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST {{HostAddress}}/api/label
Content-Type: application/json
X-GitHub-Token: {{GitHubToken}}

{
  "version": 1,
  "issue": {
    "owner": "mattleibow",
    "repo": "labeled-by-ai",
    "number": 13
  },
  "labels": {
    "names": [
    ],
    "pattern": "^area/.+"
  }
}

###
