name: Apply labels using AI

on:
  push:
    branches: 
      - dev/workflow-testing
      - dev/action-testing

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: mattleibow/labeled-by-ai@dev/workflow-testing
        with:
          label-pattern: '^area/.*'
