name: Apply labels using AI

on:
  push:
    branches: 
      - dev/workflow-testing
      - dev/action-testing

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Read the test issue json
        shell: pwsh
        id: loader
        run: |
          $issue = Get-Content ".github/workflows/test-issue.json"
          echo $issue
          $issue = $issue | Join-String -Separator " "
          echo $issue
          "GITHUB_ISSUE=$issue" >> "$GITHUB_OUTPUT"
          echo $env:GITHUB_OUTPUT
          Get-Content $env:GITHUB_OUTPUT
      - uses: mattleibow/labeled-by-ai@dev/workflow-testing
        with:
          label-pattern: '^area/.*'
          issue-json: ${{ steps.loader.outputs.GITHUB_ISSUE }} # testing pipeline only
