name: Local Testing Workflow (Read Only)

on:
  push:
    branches: 
      - action/label-with-ai

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Read the test issue json
        shell: pwsh
        id: loader
        run: |
          $issue = Get-Content ".github/workflows/test-data/test-issue.json"
          $issue = $issue | Join-String -Separator " "
          "GITHUB_ISSUE=$issue" >> $env:GITHUB_OUTPUT
      - uses: mattleibow/dev-tools@action/label-with-ai
        with:
          label-pattern: '^area/.*'
          issue-json: ${{ steps.loader.outputs.GITHUB_ISSUE }} # testing pipeline only
          apply-label: 'false'
          add-comment: 'false'
