name: Apply labels using AI

on:
  issues:
    types: [opened, reopened]

jobs:
  apply-label-and-add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: mattleibow/labeled-by-ai@main
        with:
          label-pattern: '^area/.*'
