name: Apply labels using AI

on:
  issues:
    types: [opened]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: mattleibow/labeled-by-ai@dev/action-testing
        with:
          label-pattern: '^area/.*'
