name: Local Testing Workflow (Writeable)

on:
  push:
    branches: 
      - action/label-with-ai

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Read the test issue json
        shell: pwsh
        id: loader
        run: |
          $issue = Get-Content ".github/workflows/test-data/test-issue.json"
          $issue = $issue | Join-String -Separator " "
          "GITHUB_ISSUE=$issue" >> $env:GITHUB_OUTPUT
      - uses: mattleibow/dev-tools@action/label-with-ai
        with:
          labels: |
            area/action
            area/ai
            area/function
          issue-json: ${{ steps.loader.outputs.GITHUB_ISSUE }} # testing pipeline only
