name: Labeler Testing Workflow

on:
  issue_comment: 
    types: [created]

jobs:
  test-workflow:
    if: startsWith(github.event.comment.body, '/label')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: mattleibow/dev-tools@dev/action/label-with-ai
        with:
          label-pattern: '^area/.*'
